### ISSUE TITLE
Adjust for Podman use?

### ISSUE THREAD

**Issue by bayazidbh** [joplin-vieweb/joplin-vieweb#63]
Hi, I'm a newbie in using containerised applications, I've only been mainly using distrobox with a side of experimenting with podman.

I tried to run the compose with podman installed via Nix (which means I don't have alias lists for one) a while back and even after trying to adjust a few things based on what little I understood of Docker compose, I still failed to make it run properly.

Would it be possible to create a separate installer for user-installed podman?

**Comment by gri38** [comment]
Hello.
I'm sorry, but I won't have time to try on podman.
I don't know podman, but as far as I understand, podman tries to be docker-compatible... so maybe yout issue is not about podman or docker, but elsewhere.

**I would strongly advise** you first try with docker (distrobox works with docker).
I don't know how far you've already investigate, but maybe the conclusion "it doesn't work on podman is too early).

If everything works fine, then, you can try to move to podman, and if it fails you would know the root cause is podman / docker.

Then I could adjust the project to remove possible things only compatible with docker... (even if I think I use quite basic stuff about docker).

Good luck ;-) (I remain available to help to make it work with docker, of if you have questions about the project itself. But I won't be able to find time to investigate with podman).

**Comment by bayazidbh** [comment]
Thanks for the clarification. I've currently tried it with a laptop I throw Ubuntu Server on, and using Docker installed via Snap. I still failed, but I'm pretty sure it was because I didn't really understand what I'm doing yet. I'll try to get it running there, and if it works then I'll try to slowly try to bring to my other devices running podman. Thanks for the reply.
